/**
 * What FutureBox charges, and what it costs to deliver.
 *
 * One file, so a price can never mean two different things in two places. The
 * pricing page, the entitlement caps and the checkout all read from here.
 *
 * ── The shape of it ──────────────────────────────────────────────────────
 *
 * A ladder, not a wall. Somebody who will never subscribe can still spend
 * something, and somebody who spends twice is shown that subscribing is
 * cheaper than a third purchase.
 *
 *   free      unlimited browser sketches, and two 15-second sung previews
 *             with a watermark. Costs almost nothing to give away, which is
 *             what makes it survivable — see the note on abuse below.
 *   R14       open one preview into the full-length song. Still watermarked.
 *             A taster, priced to be an easy yes rather than to cover itself.
 *   R49       keep that song: clean, downloadable, the rights are yours.
 *             Charged in full, not as an upgrade — somebody who opens first
 *             and then keeps pays R63 in total. That is a deliberate choice by
 *             the owner: the R14 is a separate, smaller product rather than a
 *             deposit against the R49, and it earns more per buyer who does
 *             both. It also means the app must never describe opening as free
 *             or as credited, because it is neither.
 *   monthly   for people making more than a couple of songs.
 *
 * ── Why the free tier is two 15-second previews ──────────────────────────
 *
 * Not meanness — arithmetic. At a 5% purchase rate every buyer carries twenty
 * free users, so the free tier is roughly 80% of the music bill. Two full
 * songs given away costs about R102 per eventual sale; two 15-second previews
 * cost about R13. The second number is a business and the first is not.
 *
 * It is also the whole anti-abuse strategy. Somebody with a hundred email
 * addresses can farm two hundred watermarked 15-second clips, and nobody
 * wants those. Make the free thing not worth stealing and there is nothing
 * left to defend.
 *
 * ── What the monthly prices have to carry ────────────────────────────────
 *
 * Fixed, per month, at R16/USD:
 *
 *   ElevenLabs Business   R15,840   the only genuinely expensive input
 *   Anthropic (copilot)    ~R1,500   small per message, adds up at volume
 *   Workshops               R4,000   production, or arranging the real thing
 *   Supabase Pro              R400
 *   Vercel Pro                R320
 *   GitHub                     R64
 *   Video                        R0   drawn in the viewer's own browser
 *                          ────────
 *                           R25,124
 *
 * Video being free is worth saying out loud: it is a permanent margin
 * advantage over anything that calls a hosted video model per clip.
 *
 * Break-even lands near 130 paying members on a 60/30/10 mix across the three
 * tiers. At 250 members the month clears roughly R23,000.
 *
 * ── Start smaller than Business ──────────────────────────────────────────
 *
 * R15,840 a month is not a day-one commitment. ElevenLabs Creator ($22) or
 * Pro ($99) carries the first few hundred members; the per-song cost is
 * roughly double, which the margins below absorb. Step up when the credit
 * ceiling actually binds, not before.
 */

import { priceFor, randDisplay, regionByCode, type LocalPrice, type Region } from './pricing';

export type Tier = 'free' | 'maker' | 'studio' | 'label';

/** Ordered cheapest first, so "the next tier up" is a list position. */
export const TIERS: readonly Tier[] = ['free', 'maker', 'studio', 'label'];

export interface TierSpec {
  readonly id: Tier;
  readonly name: string;
  /** Rand per month. Regional pricing converts from this. */
  readonly rand: number;
  /** Full-length songs included per month. */
  readonly songs: number;
  /**
   * Music videos included per month, generated by the video engine.
   *
   * A generated video costs real money per clip, so unlike the browser
   * sketches this is a counted allowance. Free is zero: nothing generated is
   * given away, and the free tier sees what the app can do through the browser
   * sketches, which cost nobody anything because they are drawn on the device.
   */
  readonly videos: number;
  /** The one line that says who it is for. */
  readonly who: string;
  readonly includes: readonly string[];
}

export const TIER_SPECS: Record<Tier, TierSpec> = {
  free: {
    id: 'free',
    name: 'Free',
    rand: 0,
    songs: 0,
    /* No video engine on the free tier, and no marked one either.

       This said one a month, watermarked, which described something that does
       not exist: a generated video costs real money per clip and none of them
       is given away. What is free here is the browser sketch — drawn on the
       device, costing nobody anything — and that has no allowance and never
       needed one. */
    videos: 0,
    who: 'Everything your own phone can make, without limit and without paying.',
    /* No generated music on the free tier either, since 8 September 2026.

       It was two half songs. ElevenLabs' real prices — $0.15 a minute, half
       the minutes per plan this repo had assumed — put nineteen free users
       behind every paying one at more music than the paying member makes, and
       that is the difference between a business that works and one that does
       not. `app/lib/credits.ts` has the numbers and
       `docs/ELEVENLABS-PRYSE.md` the derivation.

       What is left is not nothing, and the card says what it is rather than
       what it lost. Everything below costs us nothing to run, and it is the
       part people stay for. */
    includes: [
      'Unlimited browser sketches — real audio and real video, made on your own device',
      'The recording booth, with no limit at all: sing, record, mix, master',
      'Hooks, the timeline, the sound trainer and the radar',
      'Style previews, so you can hear a sound before you buy anything',
      'A generated song is on a plan — every one of them costs real money to make',
      /* ── Album art, on every plan ────────────────────────────────────
         Carli, 22 September 2026: *"Kyk ook dat die nuwe album art
         afdeling deel van die free, en betalings pakkette vorm en wys."*
         The room was built, it sells, and no package mentioned it existed.
         It is not gated by tier — `app/api/artmarket/route.ts` reads no
         tier at all — so the true line is the same on all four: the room
         is open to everybody and the artwork is paid for per piece, not
         out of credits.

         The two amounts are written out rather than imported.
         `data/artmarket.ts` imports `gatewayFee` from this file, so
         importing its constants back makes a cycle — and the cycle does
         not fail the build, it fails at module init with "Cannot access
         START_RAND before initialization", which took down three cost
         checks. `check:artmarket` holds these two numbers against
         `START_RAND` and `UNIQUE_RAND`, so the card still cannot drift
         from what the till charges. */
      'Album art by real artists — bidding opens at R200, or R500 to take a piece outright. On every plan, paid per piece.',
      /* ── The rooms that used to be free, or sold separately ───────────
         24 September 2026. Carli: *"Ek dink net ons moet ons gratis
         funksies monotise, dit moet pakkette word wat mense koop. Die
         probooth, die video editing."* And on the advert desk, which was
         R199 a month on its own: *"dit moenie 'n ekstra produk wees nie ...
         Te veel aankoop punte gaan mense afsit."*

         So there is no add-on. All three come with every paid plan, and
         what is generated inside them costs credits out of the same wallet
         as a song. The prices and their derivation are in `credits.ts`;
         `check:kredietkoste` holds each against its real upstream bill and
         `check:sold` holds these lines against the prices.

         Dubbing stays on its own line because it is the one thing a plan
         may not be able to afford: 162 credits a minute against Maker's 90
         a month. The line says which plan it starts at rather than leaving
         somebody to find the wall. */
      'The Booth is free and always will be — record, sing over a track, as many takes as you like. The Pro Booth, with lanes, the grid, mixing and undo, comes with every paid plan.',
      'Sketch a video in your own browser as much as you like. The video editor — a timeline, fades, sound under it and the filters — comes with every paid plan.',
      'The marketing desk — the market read, the week and the queue — was R199 a month on its own. It is now in every paid plan: a month\u2019s plan is 40 credits, eight advert lines 20.',
      'Dubbing an episode into another language is the dearest thing here: 162 credits a minute, so it needs Studio or Label.',
    ],
  },
  maker: {
    id: 'maker',
    name: 'Maker',
    rand: 149,
    songs: 9,
    videos: 3,
    who: 'A song or two a week, kept and posted.',
    includes: [
      '90 credits a month — 9 full songs, or 3 music videos',
      'The video engine, which the free tier does not have at all',
      'Your own voice, cloned, for reading and for the show',
      'The copilot, uncapped',
      'Post to your own channels',
      'Every workshop',
      'Album art by real artists — bidding opens at R200, or R500 to take a piece outright. On every plan, paid per piece.',
      /* ── The rooms that used to be free, or sold separately ───────────
         24 September 2026. Carli: *"Ek dink net ons moet ons gratis
         funksies monotise, dit moet pakkette word wat mense koop. Die
         probooth, die video editing."* And on the advert desk, which was
         R199 a month on its own: *"dit moenie 'n ekstra produk wees nie ...
         Te veel aankoop punte gaan mense afsit."*

         So there is no add-on. All three come with every paid plan, and
         what is generated inside them costs credits out of the same wallet
         as a song. The prices and their derivation are in `credits.ts`;
         `check:kredietkoste` holds each against its real upstream bill and
         `check:sold` holds these lines against the prices.

         Dubbing stays on its own line because it is the one thing a plan
         may not be able to afford: 162 credits a minute against Maker's 90
         a month. The line says which plan it starts at rather than leaving
         somebody to find the wall. */
      'The Pro Booth: lanes, the grid, the metronome, mixing, mastering and undo. Splitting stems is 4 credits a minute, changing a voice 4.',
      'The video editor: a timeline, fades, sound under it and export. Taking a background out is 8 credits per five seconds, an item out 11; generating a piece is priced like any clip.',
      'The marketing desk — the market read, the week and the queue. A month\u2019s plan is 40 credits; eight advert lines are 20.',
      'Dubbing is 162 credits a minute — more than this plan holds, so it starts at Studio.',
    ],
  },
  studio: {
    id: 'studio',
    /* R399 → R349 on 10 September 2026, at her instruction: "Ek dink ons moet
       die middelste pakket van ons subscription R349 maak, die marge moet
       dieselfde bly, en dus net die krediete afbring."

       So the credits came down to hold the margin, rather than the margin
       being allowed to fall out of a rounder price. Worst case a credit costs
       R0.552 (a ten-credit song costs R5.52 to make), and the gateway takes
       3.5% plus R2:

           R399, 220 credits → R399 − R121.44 − R15.97 = 65.56%
           R349 needs 191.98 credits to hold that exactly.

       190, because credits buy songs in tens and 192 sells two that cannot
       become one. It lands at 65.88% — a third of a point ABOVE where it was,
       so the instruction is met in the direction that is safe to be wrong in.

       The step up still works, which is the constraint that is easy to miss:
       Maker → Studio is now R2.00 a credit and Studio → Label R2.20, both
       still under the R2.50 top-up rate. A top-up that undercuts a step is a
       reason never to move up, and `check:topups` measures it. */
    name: 'Studio',
    rand: 349,
    songs: 19,
    videos: 6,
    who: 'Releasing regularly, and pitching for collabs.',
    includes: [
      '190 credits a month — 19 full songs, or 6 music videos',
      'Train a sound of your own on your own songs',
      'Everything in Maker, and three cloned voices',
      'Ask FutureBox to boost a collab',
      'The full radar — every item, every reason',
      'Album art by real artists — bidding opens at R200, or R500 to take a piece outright. On every plan, paid per piece.',
      /* ── The rooms that used to be free, or sold separately ───────────
         24 September 2026. Carli: *"Ek dink net ons moet ons gratis
         funksies monotise, dit moet pakkette word wat mense koop. Die
         probooth, die video editing."* And on the advert desk, which was
         R199 a month on its own: *"dit moenie 'n ekstra produk wees nie ...
         Te veel aankoop punte gaan mense afsit."*

         So there is no add-on. All three come with every paid plan, and
         what is generated inside them costs credits out of the same wallet
         as a song. The prices and their derivation are in `credits.ts`;
         `check:kredietkoste` holds each against its real upstream bill and
         `check:sold` holds these lines against the prices.

         Dubbing stays on its own line because it is the one thing a plan
         may not be able to afford: 162 credits a minute against Maker's 90
         a month. The line says which plan it starts at rather than leaving
         somebody to find the wall. */
      'The Pro Booth: lanes, the grid, the metronome, mixing, mastering and undo. Splitting stems is 4 credits a minute, changing a voice 4.',
      'The video editor: a timeline, fades, sound under it and export. Taking a background out is 8 credits per five seconds, an item out 11; generating a piece is priced like any clip.',
      'The marketing desk — the market read, the week and the queue. A month\u2019s plan is 40 credits; eight advert lines are 20.',
      'Dubbing into another language, in the same voice — 162 credits a minute out of your 190.',
    ],
  },
  label: {
    id: 'label',
    name: 'Label',
    rand: 899,
    songs: 44,
    videos: 14,
    // "Five seats on one account" was on this card and was never built —
    // nothing in the codebase adds a second person to an account. It came off
    // rather than getting a rushed implementation: an overclaim on a paid tier
    // sits on the page where money changes hands, and the one thing this app
    // cannot afford to be caught doing is describing something it does not do.
    who: 'Running a catalogue, and releasing every week.',
    includes: [
      '440 credits a month — 44 full songs, or 14 music videos',
      'Everything in Studio, and ten cloned voices',
      'The feed uncapped — every item, no daily ceiling anywhere',
      'A say in which workshops get made',
      'Album art by real artists — bidding opens at R200, or R500 to take a piece outright. On every plan, paid per piece.',
      /* ── The rooms that used to be free, or sold separately ───────────
         24 September 2026. Carli: *"Ek dink net ons moet ons gratis
         funksies monotise, dit moet pakkette word wat mense koop. Die
         probooth, die video editing."* And on the advert desk, which was
         R199 a month on its own: *"dit moenie 'n ekstra produk wees nie ...
         Te veel aankoop punte gaan mense afsit."*

         So there is no add-on. All three come with every paid plan, and
         what is generated inside them costs credits out of the same wallet
         as a song. The prices and their derivation are in `credits.ts`;
         `check:kredietkoste` holds each against its real upstream bill and
         `check:sold` holds these lines against the prices.

         Dubbing stays on its own line because it is the one thing a plan
         may not be able to afford: 162 credits a minute against Maker's 90
         a month. The line says which plan it starts at rather than leaving
         somebody to find the wall. */
      'The Pro Booth: lanes, the grid, the metronome, mixing, mastering and undo. Splitting stems is 4 credits a minute, changing a voice 4.',
      'The video editor: a timeline, fades, sound under it and export. Taking a background out is 8 credits per five seconds, an item out 11; generating a piece is priced like any clip.',
      'The marketing desk — the market read, the week and the queue. A month\u2019s plan is 40 credits; eight advert lines are 20.',
      'Dubbing into another language, in the same voice — 162 credits a minute out of your 440.',
    ],
  },
};

/**
 * The two one-off purchases, retired.
 *
 * R14 opened a preview into the whole song and R49 kept it clean. They made
 * sense when a free song was fifteen seconds of a file that already existed.
 * Credits do the same job now and do it better: five credits turns a half song
 * into a whole one, and the same five buy anything else instead.
 *
 * Keeping both was worse than either. Two prices for one outcome is a person
 * working out which is the trick, and the R14 promised to "hear the rest" of
 * something that has to be generated again — the music API takes no seed, so
 * there is no rest to hear, only a second take.
 *
 * Nothing is removed from anybody who already paid. `purchases` is still read
 * everywhere it was, so a bought track stays bought; it is only the selling
 * that has stopped.
 */

/* ────────────────────────────────────────────────────── what it costs us ─ */

/**
 * Rand to the dollar, used everywhere a supplier prices in USD.
 *
 * Exported rather than written twice. It was a `16` inside the expression
 * below and a second `16` on the line that turns the Business plan into
 * rand; `app/data/aiprices.ts` would have been the third. This app has
 * already had two meanings for one word twice, and an exchange rate that
 * disagrees with itself is every supplier's cost wrong in a different
 * direction on the same page.
 *
 * Deliberately a round number and deliberately a little pessimistic. It is
 * not a live rate and must not become one: a cost table that moves on its
 * own is a cost table nobody can check against last month's.
 */
export const RAND_PER_USD = 16;

/* ── A second cost model used to live here, and it was the wrong one ─────
 *
 * 24 September 2026, going through every sum for a budget. This file carried
 * `RAND_PER_CREDIT`, `randCost`, `SONG_COST`, `marginOf`, `FIXED_MONTHLY` and
 * `FIXED_TOTAL` — a complete second cost model, sitting in the main pricing
 * file, read by absolutely nothing.
 *
 * Which is why nobody noticed it was wrong in three separate ways at once:
 *
 *   · `RAND_PER_CREDIT` was $990 for **11 000 000** credits. ElevenLabs' own
 *     email of 9 September says 6 000 000. The rate was 45% too cheap.
 *   · `SONG_COST` therefore said "about R2.59 on Business". `credits.ts` has
 *     said since 8 September that a song is R5.52, and says so at length.
 *   · `FIXED_MONTHLY` listed GitHub at R64 — which Carli confirmed costs her
 *     nothing — and was missing Kits.AI (R640), Zoho (R241.50), the domains
 *     (R168) and Spaceship (R210.24). R1 259.74 a month of real bills absent
 *     from a list called "monthly fixed costs".
 *
 * None of it caused a visible fault, because nothing read it. It was worse
 * than a bug: it was a landmine. Anybody opening `plans.ts` to ask what the
 * business costs — which is the obvious file to open — would have found a
 * confident, itemised, wrong answer.
 *
 * The live model is `scripts/fixedcosts.mts` for the bills and
 * `scripts/costs-eleven.mts` for the arithmetic, and `docs/KOSTE-EN-WINS.md`
 * is generated from them. `fixedcosts.mts` exists because this exact fault —
 * two lists, one wrong — already happened once between a document and a
 * generator. It happened a second time, here, and this is the deletion.
 *
 * `gatewayFee` below stays: it is the one thing in this block that was both
 * correct and read. */

/**
 * The free format: half a song.
 *
 * It was fifteen seconds, because nothing capped how many of those one person
 * could ask for and the free tier was therefore priced by the clip. Credits
 * cap the month instead, so the clip itself can be worth listening to: one
 * minute, watermarked, five credits — and a full song is the same rule twice.
 */
export const PREVIEW_SECONDS = 60;
export const FREE_PREVIEWS = 2;
/** What a full song is, in minutes, for both costing and generation. */
export const SONG_MINUTES = 2;

/**
 * What a payment gateway takes. South African gateways sit near 3.5% plus a
 * couple of rand fixed, and the fixed part is what hurts: it is 18% of R14 and
 * 8% of R49. That is the known cost of a low entry price, accepted on purpose
 * because a lower step converts more people.
 */
/**
 * What the payment gateway takes, as two named numbers.
 *
 * ── Two rates for one fee, found 24 September 2026 ───────────────────────
 *
 * `docs/MAANDELIKSE-KOSTE.md` said **2.9% + R1** and marked it checked.
 * This function charged **3.5% + R2**, and this is the one that reached every
 * margin sum on every page.
 *
 * On Maker's R149 that is R5.32 against R7.22 — R1.90 a member a month, in
 * the direction that UNDERSTATES the profit. Not a disaster, and exactly the
 * same shape as the R64 that was called Resend on one page and GitHub on
 * another.
 *
 * ── Which one stands, and why ────────────────────────────────────────────
 *
 * The dearer one, until a real Paystack statement says otherwise. Scaling a
 * cost down on a figure nobody in this session could confirm is the wrong
 * direction to guess in: too low a fee makes the business look better than it
 * is, and that is the kind of error you meet at the bank rather than in a
 * test.
 *
 * **One statement settles it.** If 2.9% + R1 is right, every margin here is
 * R1.90 a member a month better than it says. `check:koste` holds the
 * document against these two numbers so they cannot drift apart again.
 */
export const GATEWAY_RATE = 0.035;
export const GATEWAY_FIXED = 2;

export function gatewayFee(rand: number): number {
  return rand * GATEWAY_RATE + GATEWAY_FIXED;
}


/* `breakEvenMembers()` stood here — a THIRD break-even calculation, built on
   the wrong rate and the incomplete bill list above, and read by nothing.

   `costs-eleven.mts` works out break-even across four ElevenLabs plans and
   four usage scenarios and writes them all into `docs/KOSTE-EN-WINS.md`. One
   number here, hard-coded to a 60/30/10 mix and a song cost that was 45% too
   cheap, could only ever have contradicted it. */

/* ──────────────────────────────────────────────────────────── display ─── */

/**
 * These prices were chosen in rand, against rand costs, for a South African
 * market. So rand is the base — not dollars.
 *
 * `pricing.ts` converts a *dollar* amount by a purchasing-power factor, which
 * means a rand figure has to be turned back into the dollar it represents
 * before it can be sent anywhere else. Dividing by the exchange rate is the
 * wrong move, and was the first thing I got wrong here: it showed R6 for a R14
 * price, because R14 of local burden is about $1.94 of pricing power rather
 * than $0.88 of currency.
 */
const ZA_PPP = regionByCode('ZA')?.pppFactor ?? 7.2;

/** What a rand price is worth as a dollar burden, for every other region. */
function asDollarBurden(rand: number): number {
  return rand / ZA_PPP;
}

/**
 * At home the number is shown exactly as chosen. `tidy()` rounds to charm
 * prices, which is right when deriving a foreign price and wrong here: it
 * turns R35 into R34, and then opening a song plus keeping it no longer adds
 * up to the R49 the app promises it will.
 */
function localised(rand: number, region: Region): LocalPrice {
  if (region.code === 'ZA') {
    return {
      amount: rand,
      currency: 'ZAR',
      // Grouped with a space, which is how a rand figure is written here.
      // `toLocaleString` gives commas, which reads as a foreign price card —
      // invisible at R49 and glaring at R180,000.
      display: randDisplay(rand),
      usd: asDollarBurden(rand),
    };
  }
  return priceFor(asDollarBurden(rand), region);
}

export function tierPrice(tier: Tier, region: Region): LocalPrice {
  const spec = TIER_SPECS[tier];
  if (spec.rand === 0) {
    return { amount: 0, currency: region.currency, display: 'Free', usd: 0 };
  }
  return localised(spec.rand, region);
}

export function oneOffPrice(rand: number, region: Region): LocalPrice {
  return localised(rand, region);
}
/**
 * What it costs to put your name on something here.
 *
 * In rand, because the audience is South African and a dollar figure on a
 * South African rate card tells a local advertiser nothing about what they are
 * being asked for. Everywhere else it converts the same way every other price
 * in this app converts.
 *
 * The entry rung is deliberately high. A rate card starting at pocket money
 * fills the inbox with people who want a backlink, and every hour spent on
 * those is an hour not spent on the one sponsor worth having. The floor is the
 * filter.
 *
 * What is sold is the thing itself, never the sides of the page: a class, a
 * season, a competition prize, or one month as the named partner. There are no
 * banners to buy because there are no banners. A sponsor's return is the
 * counters — real numbers, already on the page, the same ones everybody sees.
 */
export interface Sponsorship {
  readonly id: string;
  /** What they are actually buying. */
  readonly name: string;
  readonly from: number;
  /**
   * The top of the band, or null for a single price.
   *
   * The rungs started as bands because nothing had been sold yet and a band is
   * what you quote before you know. They are single prices now, which is a
   * better thing to put in front of somebody: a band invites a negotiation
   * before there is anything to negotiate about, and the low end of it is the
   * only number anybody remembers.
   */
  readonly to: number | null;
  /**
   * What the price is *for*, which is not the same on every rung.
   *
   * A masterclass is bought once, a season is bought once, and only the
   * headline partnership recurs. The page printed "/ month" against all three,
   * which quietly quadrupled the first two.
   */
  readonly per: 'class' | 'season' | 'month';
  readonly gets: string;
}

export const SPONSORSHIP: readonly Sponsorship[] = [
  {
    id: 'class',
    name: 'One masterclass',
    from: 5_000,
    to: null,
    per: 'class',
    gets: 'Your name on one class, set in the same type as everything else on it.',
  },
  {
    id: 'season',
    name: 'A season',
    from: 9_000,
    to: null,
    per: 'season',
    gets: 'A run of classes or episodes, named once at the top of each.',
  },
  {
    id: 'headline',
    name: 'Headline partner',
    from: 25_000,
    to: null,
    per: 'month',
    gets: 'One a month, named across the whole app — every room, not one page. Nothing that blinks.',
  },
];

/** A rung as a person in this region reads it: "R5 000 a class". */
export function sponsorshipBand(rung: Sponsorship, region: Region): string {
  const from = localised(rung.from, region).display;
  return rung.to === null ? from : `${from} – ${localised(rung.to, region).display}`;
}

/**
 * The price with what it buys, which is the only form worth showing.
 *
 * Kept next to the rungs rather than in the page, because the page had "/
 * month" hard-coded after every one of them and there is no way to read that
 * off the data — it was simply wrong for two of the three, and wrong in the
 * direction that costs a sale.
 */
export function sponsorshipPrice(rung: Sponsorship, region: Region, lang: 'en' | 'af' = 'en'): string {
  const per = {
    en: { class: 'a class', season: 'a season', month: 'a month' },
    af: { class: 'per klas', season: 'per seisoen', month: 'per maand' },
  }[lang][rung.per];
  return `${sponsorshipBand(rung, region)} ${per}`;
}

/**
 * What each tier may do in the podcast studio.
 *
 * The free tier can hear what the thing does — a short script, in a stock
 * voice, a few times a day — and cannot clone or publish. That is the line
 * that matters: a clone is the expensive, consequential thing, and publishing
 * puts a file on the open internet under somebody's name. Neither belongs
 * behind no commitment at all.
 */
export interface PodcastCaps {
  /** How many cloned voices this tier may keep. Zero means none. */
  readonly voices: number;
  /** Characters in one script. A cap here is a cap on the bill. */
  readonly speakChars: number;
  readonly speakPerDay: number;
  /** Their audio isolation, on a recording made here. */
  readonly clean: boolean;
  /** A show with a feed that podcast apps can subscribe to. */
  readonly publish: boolean;
}

export const PODCAST_CAPS: Record<Tier, PodcastCaps> = {
  free: { voices: 0, speakChars: 400, speakPerDay: 3, clean: false, publish: false },
  maker: { voices: 1, speakChars: 3_000, speakPerDay: 20, clean: true, publish: true },
  studio: { voices: 3, speakChars: 6_000, speakPerDay: 60, clean: true, publish: true },
  label: { voices: 10, speakChars: 12_000, speakPerDay: 200, clean: true, publish: true },
};

/**
 * How many trained sounds of your own a tier may keep.
 *
 * Training is not a request, it is ten minutes of somebody else's GPUs, and
 * the model then sits on the account until it is deleted. So this is a small
 * number everywhere and zero on free — not to withhold the feature, but
 * because an unbounded one is a bill nobody agreed to.
 */
export const SOUND_CAPS: Record<Tier, number> = {
  free: 0,
  // Not on Maker. Training costs 300 credits and Maker's whole month is 120,
  // so "one trained sound" on that card was a thing the plan could not pay
  // for — a promise redeemable only by buying a pack. Better to say plainly
  // that it starts at Studio.
  maker: 0,
  studio: 3,
  label: 10,
};
