'use client';

/**
 * The tick box that makes an account an agreement.
 *
 * ── Why it exists ────────────────────────────────────────────────────────
 *
 * Until 15 September 2026 nothing on the sign-up screen mentioned the terms
 * at all — not a link, let alone a box. That is not a style problem. The
 * ElevenLabs OEM Terms are the document that lets FutureBox pass their music
 * and voice service through to its own members, and their §3(A) says every
 * member must have accepted "a written contract, or 'clickwrap' style online
 * agreements involving conspicuous notice to End Users and an affirmative
 * click to accept". A footer link is neither conspicuous notice nor an
 * affirmative click. The permission the whole product rests on is conditioned
 * on this box.
 *
 * ── Why it is one box and not three ──────────────────────────────────────
 *
 * The honest instinct is a box each for the terms, the privacy policy and
 * being 18. Three boxes is also how you teach somebody to tick without
 * reading. One sentence that says all three, with both documents linked in
 * it, is conspicuous in the way the clause means — it is in the way, it is
 * unticked, and the button does not work until it is read past.
 *
 * ── Why the links open elsewhere ─────────────────────────────────────────
 *
 * `target="_blank"`, which is normally a smell. Here it is the point: this
 * sits in a modal over a half-filled form, and sending somebody to /terms in
 * the same tab throws away the email and password they just typed. Coming
 * back to an empty form is how people stop reading the terms.
 *
 * ── Sign-up only ─────────────────────────────────────────────────────────
 *
 * The caller decides. Signing back in is not a new agreement, and asking
 * somebody to re-accept every time they sign in makes the record meaningless
 * — the acceptance that matters is the one at the start, kept with its date.
 */

import React from 'react';
import Link from 'next/link';
import { useLang } from '../lib/i18n';

export default function AgreeToTerms({
  checked,
  onChange,
}: {
  readonly checked: boolean;
  readonly onChange: (next: boolean) => void;
}): React.ReactElement {
  const { t } = useLang();
  const link = 'text-emerald-400 hover:text-emerald-300 underline underline-offset-2';

  return (
    <label className="flex items-start gap-3 cursor-pointer select-none rounded-xl border border-zinc-800 bg-black/40 p-3">
      <input
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
        /* 20px, not the browser default. A 13px target beside two paragraphs
           of small text is the one control on this screen somebody has to hit
           with a thumb. */
        className="mt-0.5 h-5 w-5 shrink-0 accent-emerald-500 cursor-pointer"
      />
      <span className="text-xs text-zinc-400 leading-relaxed">
        {t('auth.agreeAge', 'I am 18 or older, and I accept the')}{' '}
        <Link href="/terms" target="_blank" rel="noopener noreferrer" className={link}>
          {t('auth.agreeTerms', 'terms')}
        </Link>{' '}
        {t('common.and', 'and')}{' '}
        <Link href="/privacy" target="_blank" rel="noopener noreferrer" className={link}>
          {t('auth.agreePrivacy', 'privacy policy')}
        </Link>
        {t('auth.agreeTail', ', including that music, voices and the copilot are generated by other companies and that what I send goes to them.')}
      </span>
    </label>
  );
}
