'use client';

/**
 * Music video — the screen that turns one of your songs into something to watch.
 *
 * It replaced a page that asked for a link to a song made somewhere else and
 * then talked about publishing. This one only knows about songs you made here:
 * pick one, choose the shape and the length, and the video is drawn in this
 * browser from the track's own audio. It plays on this page when it is done.
 * Saving it or sharing it is your call, afterwards.
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Video as VideoIcon, Loader2, Music, Plus, Trash2 } from 'lucide-react';
import { loadTracks, type Track } from '../lib/library';
import * as cloud from '../lib/cloud';
import { getAudio } from '../lib/library';
import VideoPanel from './VideoPanel';
import { useLang } from '../lib/i18n';
import { useCopilotOps, matchByTitle } from '../lib/copilotactions';
import { addUpload, loadUploads, removeUpload } from '../lib/uploads';
import Note from './Note';
import Card from './Card';
import Storyboard from './Storyboard';
import { probeVideoEngine, type EngineAspect, type VideoGrades } from '../lib/engines';
import { LENGTHS } from '../lib/videoscenes';
import type { VideoGrade } from '../lib/credits';

export default function MusicVideo() {
  const { t } = useLang();
  const [tracks, setTracks] = useState<Track[]>([]);
  /** Songs brought in from a file. Beside the channel, never in it. */
  const [brought, setBrought] = useState<Track[]>([]);
  const [selected, setSelected] = useState<Track | null>(null);
  const [taking, setTaking] = useState(false);
  const [problem, setProblem] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement | null>(null);

  /* Choose which song the video is for. Nothing is generated by this — it opens
     the panel, and the paid step is still a button they press. */
  useCopilotOps('video', {
    pick_song: (value) => {
      const track = matchByTitle(tracks, value);
      if (track) setSelected(track);
    },
  });

  useEffect(() => {
    const local = loadTracks();
    setTracks(local);
    setBrought(loadUploads());
    if (!cloud.configured()) return;
    let live = true;
    cloud.syncChannel(local, getAudio).then((merged) => {
      if (live) setTracks(merged);
    });
    return () => {
      live = false;
    };
  }, []);

  /* A song off the device.

     The room only ever read the channel, which meant a video was impossible
     for a recording made anywhere else. The file is decoded before it is
     kept, so one this browser cannot play is refused with a sentence rather
     than with a silent video. */
  const bringIn = useCallback(async (file: File | null) => {
    if (!file) return;
    setTaking(true);
    setProblem(null);
    try {
      const added = await addUpload(file);
      setBrought(loadUploads());
      setSelected(added);
    } catch (error) {
      const why = error instanceof Error ? error.message : '';
      setProblem(
        why === 'too-big'
          ? t('board.songTooBig', 'That file is over 60 MB. Trim it or export it smaller.')
          : t('board.songUnreadable', 'This browser could not read that audio. MP3, WAV or M4A work.'),
      );
    } finally {
      setTaking(false);
    }
  }, [t]);

  const dropOne = useCallback(async (id: string) => {
    await removeUpload(id);
    setBrought(loadUploads());
    setSelected((was) => (was?.id === id ? null : was));
  }, []);

  /* What the engine will actually make, asked once. The board below needs
     real lengths and shapes; guessing them is how a desk offers a length the
     engine refuses two minutes and one charge later. */
  const [engine, setEngine] = useState<VideoGrades | null>(null);
  useEffect(() => {
    let alive = true;
    void probeVideoEngine().then((found) => {
      if (alive) setEngine(found);
    });
    return () => {
      alive = false;
    };
  }, []);

  const [grade] = useState<VideoGrade>('standard');
  const [aspect] = useState<EngineAspect>('9:16');
  const able = engine?.can?.[grade];
  const lengths = LENGTHS.filter((one) => (able?.seconds ?? [5, 10]).includes(one.seconds));

  /**
   * Which of the two this room is being used for.
   *
   * A single clip and a whole music video are different jobs, and showing the
   * furniture for both at once is the busiest this room could be. So it is one
   * question after the song, and the answer decides what is on screen.
   */
  const [making, setMaking] = useState<'clip' | 'film' | null>(null);

  return (
    <div className="space-y-5">
      <div>
        <h4 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
          <VideoIcon className="w-6 h-6 text-amber-400" />
          {t('rail.video')}
        </h4>
        <p className="text-base text-zinc-400 pt-1 max-w-2xl leading-relaxed">{t('video.sub')}</p>
      </div>

      {/* ── Which song ───────────────────────────────────────────────────

          The channel first, then anything brought in from the device, then
          the button that brings one in. An empty channel is no longer a dead
          end: the room used to print "no songs yet" and stop, which was the
          wrong answer for anybody who already has a recording. */}
      {/* Boxed, like every other room. This was a loose paragraph over a row
          of chips with no card around any of it. */}
      <Card title={t('video.whichSong', 'Which song?')}>
        <p className="text-sm text-zinc-400">
          {tracks.length === 0 && brought.length === 0 ? t('video.none') : t('video.pick')}
        </p>
        <div className="flex flex-wrap gap-2">
          {[...tracks, ...brought].map((track) => (
            <button
              key={track.id}
              type="button"
              onClick={() => setSelected(track)}
              className={`px-3 py-2 rounded-xl text-sm border transition-all flex items-center gap-2 ${
                selected?.id === track.id
                  ? 'bg-emerald-500/15 border-emerald-500 text-emerald-300 font-semibold'
                  : 'bg-zinc-950/60 border-zinc-800 text-zinc-400 hover:border-zinc-600 hover:text-zinc-200'
              }`}
            >
              <Music className="w-3.5 h-3.5" />
              {track.title}
            </button>
          ))}

          <button
            type="button"
            onClick={() => fileRef.current?.click()}
            disabled={taking}
            className="px-3 py-2 rounded-xl text-sm border border-zinc-700 bg-zinc-900 text-zinc-300 hover:text-white hover:border-zinc-600 transition-all flex items-center gap-2 disabled:opacity-50"
          >
            {taking ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Plus className="w-3.5 h-3.5" />}
            {t('board.bringSong', 'Bring a song in')}
          </button>
          <input
            ref={fileRef}
            type="file"
            accept="audio/*"
            className="hidden"
            onChange={(event) => {
              void bringIn(event.target.files?.[0] ?? null);
              event.target.value = '';
            }}
          />

          {selected?.source === 'upload' && (
            <button
              type="button"
              onClick={() => void dropOne(selected.id)}
              className="px-3 py-2 rounded-xl text-sm border border-zinc-800 bg-zinc-950/60 text-zinc-400 hover:text-zinc-200 hover:border-zinc-600 transition-all flex items-center gap-2"
            >
              <Trash2 className="w-3.5 h-3.5" />
              {t('board.dropSong', 'Take it back out')}
            </button>
          )}
        </div>
        <Note className="text-xs text-zinc-500">
          {t(
            'video.bringWhy',
            'A song you made here, or an audio file off this device — up to 60 MB. A brought-in song stays on this device and is not put on your channel.',
          )}
        </Note>
        {problem && <p className="text-sm text-amber-400 leading-snug">{problem}</p>}
      </Card>

      {/* ── One clip, or the whole thing ──────────────────────────────────

          The room is called Musiekvideo and it made one clip. Everything that
          makes a *music video* — the shot list, the look they share, the words
          on screen, the trim, and cutting them into one file — lived in the
          Video desk next door, which is not where anybody goes looking for it:

            "die music video het steeds nie 'n editing bar om woorde in te sit
             nie, en goeie video editing funksies nie."

          The board is the same one the desk uses, not a second copy, and it is
          handed the song this room already asked about rather than asking
          again. */}
      {selected && making === null && (
        <Card title={t('video.whatKind', 'What are you making?')}>
          <div className="grid gap-2 sm:grid-cols-2">
            <button
              type="button"
              onClick={() => setMaking('film')}
              className="rounded-xl border border-zinc-700 bg-zinc-950/60 p-3 text-left hover:border-emerald-500"
            >
              <p className="text-sm font-bold text-white">{t('video.kindFilm', 'A music video')}</p>
              <p className="pt-1 text-sm text-zinc-400 leading-snug">
                {t(
                  'video.kindFilmWhy',
                  'Shot by shot, with the words on screen and the song underneath. Write the scenes, make them one at a time, cut them into one file.',
                )}
              </p>
            </button>
            <button
              type="button"
              onClick={() => setMaking('clip')}
              className="rounded-xl border border-zinc-700 bg-zinc-950/60 p-3 text-left hover:border-emerald-500"
            >
              <p className="text-sm font-bold text-white">{t('video.kindClip', 'One clip')}</p>
              <p className="pt-1 text-sm text-zinc-400 leading-snug">
                {t('video.kindClipWhy', 'A single shot from this song — the quickest thing to post.')}
              </p>
            </button>
          </div>
        </Card>
      )}

      {selected && making !== null && (
        <button
          type="button"
          onClick={() => setMaking(null)}
          className="text-sm text-zinc-400 hover:text-emerald-300"
        >
          {t('video.otherKind', '\u2190 Make something else with this song')}
        </button>
      )}

      {selected && making === 'film' && (
        <Storyboard aspect={aspect} grade={grade} lengths={lengths} frame={null} songId={selected.id} />
      )}

      {selected && making === 'clip' && (
        <VideoPanel track={selected} onClose={() => setSelected(null)} />
      )}
    </div>
  );
}
